"""Exploratory data analysis.

Writes a markdown report to `ml/reports/eda.md`::

    python -m ml.eda

The point is not decoration: this is where the dataset's synthetic structure —
uniform 120 rows per disease, 93.8% duplicates, zero label ambiguity — becomes
visible, and those findings drive every later decision about splitting and how
the metrics should be read.
"""

from __future__ import annotations

from collections import Counter

from ml.config import REPORTS_DIR
from ml.dataset import load_cases, load_symptom_severity


def build_report() -> str:
    cases, stats = load_cases()
    severity = load_symptom_severity()

    symptom_counts = Counter(symptom for case in cases for symptom in case.symptoms)
    symptoms_per_case = [len(case.symptoms) for case in cases]
    label_counts = stats.label_counts

    rarest = sorted(label_counts.items(), key=lambda item: item[1])[:5]
    commonest = sorted(label_counts.items(), key=lambda item: -item[1])[:5]

    lines: list[str] = [
        "# EDA — disease–symptom dataset",
        "",
        "Generated by `python -m ml.eda`. Do not edit by hand.",
        "",
        "## 1. Shape",
        "",
        "| Metric | Value |",
        "| --- | --- |",
        f"| Rows in raw file | {stats.raw_rows:,} |",
        f"| Exact duplicate rows | {stats.duplicate_rows:,} ({stats.duplicate_fraction:.1%}) |",
        f"| **Unique (disease, symptom-set) cases** | **{stats.unique_cases:,}** |",
        f"| Distinct diseases | {stats.n_labels} |",
        f"| Distinct symptoms | {stats.n_symptoms} |",
        f"| Symptom sets mapping to >1 disease | {stats.ambiguous_symptom_sets} |",
        "",
        "## 2. What these numbers mean",
        "",
        "The raw file holds **exactly 120 rows per disease** for all 41 diseases —",
        "a uniformity no real clinical sample has. After deduplication only",
        f"{stats.unique_cases} distinct cases remain, between",
        f"{min(label_counts.values())} and {max(label_counts.values())} per disease.",
        "",
        "Inspecting one disease shows how the rows were generated: the distinct",
        "symptom sets for a condition are the leave-one-out subsets of a single",
        "canonical set. The data is a **deterministic lookup table**, which the",
        f"ambiguity count confirms — {stats.ambiguous_symptom_sets} symptom sets map to more",
        "than one disease, so the label is a pure function of the features.",
        "",
        "Two consequences drive the rest of the pipeline:",
        "",
        "1. **Splitting before deduplication leaks.** Copies of the same record",
        "   would land in both train and test, and the reported score would",
        "   measure memorisation. Deduplication happens first, always.",
        "2. **A high score is not evidence of clinical skill.** Any model that",
        "   can represent a lookup table will score near-perfectly. The honest",
        "   test is robustness to inputs that are *not* in the table, which is",
        "   why training also reports a perturbation evaluation.",
        "",
        "## 3. Class distribution (after deduplication)",
        "",
        f"Mildly imbalanced: {min(label_counts.values())}–{max(label_counts.values())} cases per class,",
        f"mean {sum(label_counts.values()) / len(label_counts):.1f}.",
        "Not severe enough to warrant resampling; stratified splitting and",
        "macro-averaged metrics handle it, and synthetic oversampling of a",
        "synthetic dataset would add noise rather than information.",
        "",
        "| Fewest cases | n | | Most cases | n |",
        "| --- | --- | --- | --- | --- |",
    ]
    for (rare_label, rare_n), (common_label, common_n) in zip(rarest, commonest, strict=False):
        lines.append(f"| {rare_label} | {rare_n} | | {common_label} | {common_n} |")

    lines += [
        "",
        "<details><summary>Full class distribution</summary>",
        "",
        "| Disease | Cases |",
        "| --- | --- |",
    ]
    lines += [f"| {label} | {count} |" for label, count in label_counts.items()]
    lines += [
        "",
        "</details>",
        "",
        "## 4. Symptoms",
        "",
        "| Metric | Value |",
        "| --- | --- |",
        f"| Vocabulary size | {stats.n_symptoms} |",
        f"| Symptoms per case (min/mean/max) | {min(symptoms_per_case)} /"
        f" {sum(symptoms_per_case) / len(symptoms_per_case):.1f} / {max(symptoms_per_case)} |",
        f"| Severity weights available | {len(severity)} |",
        "",
        "Ten most frequent symptoms:",
        "",
        "| Symptom | Cases | Severity |",
        "| --- | --- | --- |",
    ]
    lines += [
        f"| {symptom} | {count} | {severity.get(symptom, '—')} |"
        for symptom, count in symptom_counts.most_common(10)
    ]

    singletons = [symptom for symptom, count in symptom_counts.items() if count == 1]
    lines += [
        "",
        f"{len(singletons)} symptoms appear in only one case. They are perfectly",
        "predictive of their disease within this dataset and are exactly the",
        "features that will not generalise.",
        "",
        "## 5. Limitations",
        "",
        "- Synthetic/templated, not real patient records.",
        "- No age, sex, duration, severity-of-episode or laboratory values, so",
        "  the model cannot use them however useful they would be clinically.",
        "- 41 diseases is a tiny fraction of what a patient could present with;",
        "  anything outside the list will be forced into one of these classes.",
        "- Symptoms are binary — no notion of how severe or how long.",
        "- Provenance of the labelling is undocumented upstream.",
        "",
        "These are limitations of the *data*, not bugs in the pipeline, and they",
        "are why MedAnalyser presents output as possible conditions requiring",
        "professional evaluation rather than as a diagnosis.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    report = build_report()
    destination = REPORTS_DIR / "eda.md"
    destination.write_text(report)
    print(f"Wrote {destination} ({len(report.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
